=== hmmlopez/jade/jade-vaadin-cockpit/src/main/resources/jadesettings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by Andreas Pueschel (APL Software GmbH) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="settings" type="settingsType"/>
	<xs:element name="profiles" type="profilesType"/>
	<xs:element name="profile" type="profileType"/>
	<xs:element name="globals" type="globalsType"/>
	<xs:complexType name="globalsType">
		<xs:choice>
			<xs:sequence>
				<xs:element ref="includes"/>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:sequence>
				<xs:element ref="includes" minOccurs="0"/>
				<xs:element ref="params"/>
			</xs:sequence>
		</xs:choice>
	</xs:complexType>
	<xs:element name="includes" type="includesType"/>
	<xs:complexType name="includesType">
		<xs:sequence>
			<xs:element ref="include" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="profileType">
		<xs:choice>
			<xs:sequence>
				<xs:element ref="includes"/>
				<xs:element ref="params" minOccurs="0"/>
			</xs:sequence>
			<xs:sequence>
				<xs:element ref="includes" minOccurs="0"/>
				<xs:element ref="params"/>
			</xs:sequence>
		</xs:choice>
		<xs:attribute ref="name" use="required"/>
	</xs:complexType>
	<xs:complexType name="profilesType">
		<xs:sequence>
			<xs:element ref="profile" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="settingsType">
		<xs:sequence>
			<xs:element ref="globals" minOccurs="0"/>
			<xs:element ref="profiles"/>
			<xs:element ref="fragments"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="include" type="includeType"/>
	<xs:complexType name="includeType">
		<xs:attribute ref="name" use="required"/>
	</xs:complexType>
	<xs:attribute name="name" type="xs:string"/>
	<xs:element name="params">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="paramsType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="paramsType">
		<xs:sequence>
			<xs:element ref="param" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="param" type="paramType"/>
	<xs:complexType name="paramType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="name" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:attribute name="value" type="xs:string"/>
	<xs:complexType name="sourceType">
		<xs:complexContent>
			<xs:extension base="profileType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="targetType">
		<xs:complexContent>
			<xs:extension base="profileType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="generalType">
		<xs:complexContent>
			<xs:extension base="profileType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:element name="source" type="sourceType"/>
	<xs:element name="target" type="targetType"/>
	<xs:element name="general" type="generalType"/>
	<xs:element name="fragments" type="fragmentsType"/>
	<xs:complexType name="fragmentType"/>
	<xs:complexType name="fragmentsType">
		<xs:sequence>
			<xs:element ref="generals" minOccurs="0"/>
			<xs:element ref="sources" minOccurs="0"/>
			<xs:element ref="targets" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="targets" type="targetsType"/>
	<xs:complexType name="sourcesType">
		<xs:sequence>
			<xs:element ref="source" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="sources" type="sourcesType"/>
	<xs:complexType name="targetsType">
		<xs:sequence>
			<xs:element ref="target" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="generalsType">
		<xs:sequence>
			<xs:element ref="general" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="generals" type="generalsType"/>
</xs:schema>

=== hmmlopez/jade/jade-vaadin-cockpit/src/main/resources/jadesettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSPY v5 rel. 3 U (http://www.xmlspy.com)-->
<settings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\Eclipse Workspace\js_workspace\products\jade\jade-vaadin-cockpit\src\main\resources\jadesettings.xsd">
	
	<globals>
		<params>
			<param name="test" value="test" />
		</params>
	</globals>
	
	<profiles>
		<profile name="local2ftp">
			<params>
				<param name="operation" value="send" />
			</params>
		</profile>
		<profile name="local2sftp">
			<includes>
				<include name="wilma_target_host" />
				<include name="wilma_target_user" />
				<include name="localhost_source" />
			</includes>
			<params>
				<param name="operation" value="send" />
			</params>
		</profile>
	</profiles>
	
	<fragments>
		<generals>
			<general name="MailSettings">
				<params>
					<param name="mail_on_error" value="true"></param>
				</params>
			</general>
		</generals>
		<sources>
			<source name="localhost_source">
				<params>
					<param name="host" value="localhost" />
				</params>
			</source>
		</sources>
		<targets>
			<target name="wilma_target_host">
				<params>
					<param name="host" value="wilma.sos" />
				</params>
			</target>
			<target name="wilma_target_user">
				<params>
					<param name="ssh_auth_method" value="password" />
					<param name="user" value="test" />
					<param name="password" value="12345" />
				</params>
			</target>
		</targets>
	</fragments>
	
</settings>
